
name: Run CASR
on:
  push:

jobs:
  run-casr:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.java }} Run CASR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 2178bd8b80d372ba2575176ac609e070ce5696f8
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Install rust and dependencies
      run: | 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y        
        sudo apt install gdb lsb-release
    - name: Install casr
      run: |
        cargo install casr
    - name: Install pnpm
      run: |
        npm install -g pnpm
    - name: Compile using gradle
      run: |
        ./gradlew clean build -x test
    - name: Run CASR
      run: |
        find . -name '*.jar' -exec sh -c '
          for jarfile; do
            echo "Processing $jarfile"
            timeout 60s casr-java -o "$jarfile.casrep" -- java -jar "$jarfile" || echo "Failed to process $jarfile" >> error.log
          done
        ' sh {} +    
    - name: List any casr reports created
      run: |
        find . -type f -name "*.casrep"
